### ISSUE TITLE
✨ [Feature] - 정책

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#17]
### ✅ To Do List

---
- [x] 정책 조회 (필터)
- [ ] 정책 상세 페이지 (단일)
- [ ] 정책 검색
- [ ] 정책 스크랩

### 📚 Etc

---

## 정책 리스트 조회
policyName, policyHost, startDate, endDate, keyword, imageUrl

## 정책 단일조회
policyName, policyHost, startDate, endDate, keyword, imageUrl
target, benefit, target, linkurl

**Comment by potatoj1n** [comment]
- 정책 시작일, 마감일 안들어옴
- 키워드 병원이랑 다르게 줄거야? Mapping으로 안주고 그냥 string으로?
- 마감 몇 일 남았는지는 내가 계산 해야하는지
- 여기있는  linkUrl이 이미지가 아니라 혹시 저 페이지 바로가기니...?
![image](https://github.com/user-attachments/assets/382a6117-bb87-41cf-a848-f29fa88758b8)

**Comment by saokiritoni** [comment]
> * 정책 시작일, 마감일 안들어옴
> * 키워드 병원이랑 다르게 줄거야? Mapping으로 안주고 그냥 string으로?
> * 마감 몇 일 남았는지는 내가 계산 해야하는지
> * 여기있는  linkUrl이 이미지가 아니라 혹시 저 페이지 바로가기니...?
ok ~

아마 그럴걸? 나한테는 그냥 String 이양
