### ISSUE TITLE
✨ [Feature] - 전체 communiy

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#26]
### ✅ To Do List

---
- [x] 커뮤니티 crud
- [x] 커뮤니티 type: 홈(전체), 심리케어, 멘토링, 정책, 병원/클리닉
- [x] 댓글 crd
- [x] 게시글 목록 조회, 게시글 단일 조회
- [x] 태그
- [x] 홈에서는 type 별 인기 글 제공 -2 
- [x] 타입별 조회
- [x] 글 사진 s3 추가
- [ ] 반환값 체크

### 📚 Etc

---
-

**Comment by yoonth95** [comment]
@saokiritoni 

현재 전체 커뮤니티 글을 조회하는 API가 있는데, 커뮤니티 글이 많아지면 오히려 성능이 안 좋을 것 같아요
그리고 지금도 디자인을 보면 커뮤니티 페이지에서는 각 타입마다 최대 2개씩 보여주고 있어서
커뮤니티 전체 조회 말고 각 타입 별 게시글 조회로 바꿔주시면 좋을 것 같아요.!

<img src="https://github.com/user-attachments/assets/eabf9253-1d79-4ec1-bd41-039b0054347c" width="30%" />

**Comment by yoonth95** [comment]
@saokiritoni 

<img src="https://github.com/user-attachments/assets/dba69dc5-990c-4a67-93c8-4accdd276f2e" width="40%" />

커뮤니티 게시글 생성할 때, content, type, photoUrls, tags 가 있어야 될 것 같아요.!
조회할 때도 4가지 있으면 될 것 같습니다.!
다만 이제 photoUrls, tags 이 2개는 선택 사항이에요

**Comment by saokiritoni** [comment]
@yoonth95 아아 네 ~~~ 전체 조회는 테스트용으로 만들어둔 거였어요!! 지금 계속 수정하고 있습니다! 좀만 기다려주세요!

**Comment by yoonth95** [comment]
@saokiritoni 

아... 제가 앞서갔었네요 넵! 감사합니다

**Comment by saokiritoni** [comment]
@yoonth95 혹시 제가 글 수도 계산해서 보내드려야 할까요? 디자인에 보면 그렇게 되어있던데 제가 할까요 아니면 프론트에서 할까요?

**Comment by yoonth95** [comment]
@saokiritoni 

타입 별 전체 글 갯수 말씀하시는 거죠?
이게 너무 많아지면 무한 스크롤링을 구현할 생각인데 무한 스크롤링을 하게 되면 게시글 갯수는 보내주시는 게 좋고
그렇지 않다면 안 보내 주셔도 됩니다.! 프론트에서 처리하면 되는 거라

지금 당장은 무한 스크롤링이 필요 없기도 하고 구현하는데 백엔드도 그렇고 프론트도 그렇고 조금 시간이 필요할 것 같아서 나중에 수정하는 걸로 하고  
일단은 타입 별 전체 게시글만 보내주세요.! 갯수까지는 필요없습니다.

**Comment by yoonth95** [comment]
@saokiritoni 

타입 별 2개씩 인기 조회 기능 서버 500 에러 납니다...

**Comment by yoonth95** [comment]
@saokiritoni 

커뮤니티 게시글 댓글에 날짜가 없습니다...

**Comment by yoonth95** [comment]
@saokiritoni 

커뮤니티 게시글 댓글도 수정 API 부탁드립니다.!

**Comment by yoonth95** [comment]
@saokiritoni 

커뮤니티 수정할 때 content, type만 되고 이미지랑 태그는 수정이 안 됩니다...
