### ISSUE TITLE
✨ [Feature] - 저장한 글

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#28]
### ✅ To Do List

---
- [x] 내 피드
- [x] 커뮤니티
- [ ] 반환값 체크

### 📚 Etc

---
-

**Comment by yoonth95** [comment]
@saokiritoni 

피드 board 글 저장이 안 돼요 서버 에러가 뜹니다...
![image](https://github.com/user-attachments/assets/7c045a56-19c2-4fb5-8ab1-3d6d02379d8a)
