### ISSUE TITLE
✨ [Feature] - 유저

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#3]
### ✅ To Do List

---
- [x] 회원가입
- [x] 로그인
- [x] 로그아웃
- [x] 프로필 수정
- [x] 프로필 조회
- [x] 내 스크랩 내역 조회
- [x] 부부 연결 (x)
- [x] 거주 지역 추가 및 수정
- [x] 프로필 사진
- [x] 내 정보 페이지 - 내 포인트, 동반자 포인트, 내 생년월일
- [x] 회원 가입 날짜

### 📚 Etc

---
- 내 스크랩은 정책 및 병원 완료 후 구현

**Comment by potatoj1n** [comment]
유저 프로필 줄 때 데이터 이렇게 필요합니다.
![image](https://github.com/user-attachments/assets/ec731a71-2246-4a9d-857e-da0606f00e43)

**Comment by saokiritoni** [comment]
> 유저 프로필 줄 때 데이터 이렇게 필요합니다. !


반영 완료 했습니당

**Comment by potatoj1n** [comment]
아직 userId, coupleUserId가 안들어와요
![image](https://github.com/user-attachments/assets/46016c82-4ed1-4edf-8420-1fc77b3b3547)

**Comment by saokiritoni** [comment]
> 아직 userId, coupleUserId가 안들어와요 !

@potatoj1n 
은지나 userId 를 직접 보내는 게 이상해서 어차피 잔액 때문에 유저 아이디 필요한 거자나! balance가 내 잔액이구 coupleBalance로 구분해서 보냈는데 그래도 유저아이디 필요함?>? 어디서 필요한거임

**Comment by potatoj1n** [comment]
잔액 아니고 거래 내역에서 상대방꺼랑 본인 꺼 비교하려면 뭔가 있어야하는데 너가 거래 내역에 유저아이디 보내주길래 그거 받아서 거래 내역에서 유저아이디 대조해서 구분하려했어
- 상대 아이디는 필요 없는데 유저 아이디는 줘야할 듯

![image](https://github.com/user-attachments/assets/40347462-c96f-40e3-9dac-0202c06626a9)

**Comment by saokiritoni** [comment]
@potatoj1n 줄 때 구분해서 보내줄게!!

**Comment by yoonth95** [comment]
@saokiritoni 

<img src="https://github.com/user-attachments/assets/146dd2d0-1300-4797-bbd5-c73f10de2941"  width="30%" />

그리고 회원 가입 날짜가 없는데 만들어 주실 수 있나요? 처음에 필요 없다 생각했었는데 캘린더 페이지에서 유저가 가입한 날짜부터 보여줘야 하다보니까 가입 날짜가 필요할 것 같습니다

**Comment by saokiritoni** [comment]
@yoonth95 5분정도 뒤에 캘린더 확인해보시면 됩니다!
