### ISSUE TITLE
✨ [Feature] - 병원

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#34]
### ✅ To Do List

---
- [x] 병원 조회 (region, middle, detail)
- [x] 키워드로 병원 조회 (한방진료, 야간진료, 주말진료, 정부지원, 체중관리, 여의사)
- [x] type으로 병원 조회 (전체, 산부인과, 비뇨기과)
- [x] 리스트
- [x] 단일
- [ ] 병원 검색

### 📚 Etc

---
- specification 쓰지말고 그냥 jpql로 바꾸기

**Comment by potatoj1n** [comment]
병원 리스트( 필터링/ 검색 반환값)에 linkUrl(이미지)가 없어요
- 데이터는 나중에 넣어도 디자인에 있어서 필요함
![image](https://github.com/user-attachments/assets/e28dec11-6f1a-4587-a407-b26df42e1c99)

**Comment by saokiritoni** [comment]
@potatoj1n  5 - 10 분뒤에 체크해주세용 추가 완
