### ISSUE TITLE
✨ [Feature] - 피드: Board

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#5]
### ✅ To Do List

---
- [x] 글쓰기
- [x] 기본 글 조회(전체)
- [x] 기본 글 조회(단일)
- [x] 글 수정
- [x] 글 삭제
- [x] 좋아요 달기
- [x] 좋아요 취소
- [x] 댓글 달기
- [x] 댓글 삭제
- [x] board 작성자 아이디 함께 반환 (상대가 썼는지 내가 썼는지 확인용)
- [x] likedByUser

### 📚 Etc
- [x] advanced 글 조회(프로필, 이름, 작성시간, 좋아요, 댓글)
- [x] advanced 글 작성 (사진 추가)

---
- 글, 댓글, 날짜별로 조회 가능하도록 (글)
- 좋아요 수 같이 조회되게 수정하기

**Comment by yoonth95** [comment]
![image](https://github.com/user-attachments/assets/7a5d33ad-d9ed-4c85-b5be-5cad9cb3fe47)

현재 board에 title이 있는데, 타이틀이 필요가 없습니다. 빼주실 수 있나요

**Comment by yoonth95** [comment]
![image](https://github.com/user-attachments/assets/f7884ad9-7cab-4b0e-9655-16d4a5cd81e5)

board나 감정 글에서는 생성 시간이 있습니다. 현재 feedDate가 2024-11-11 처럼 일까지만 나오는데, 시간도 나오게 할  수 있을까요? 아니면 createdAt을 넣어주셔도 됩니다

**Comment by saokiritoni** [comment]
> 글에서는 생성 시간이 있습니다. 현재 feedDate가 2024-11-11 처럼 일까지만 나오는데, 시간도 나오게 할 수 있을까요? 아니면 cr


@yoonth95 
feed-controller : GET /api/feeds/{date} 열어보시면 userBoards 결과에는 updatedAt이 함께 들어가는 거로 해놓았었는데, 어느 부분을 말씀하시는 걸까요?!

**Comment by saokiritoni** [comment]
> 현재 board에 title이 있는데, 타이틀이 필요가 없습니다. 빼주실 수 있나요


@yoonth95 
반영 완료 했습니다!

**Comment by yoonth95** [comment]
@saokiritoni 
<img src="https://github.com/user-attachments/assets/9338122c-032e-4ff1-96b7-76686f9d031f" width="30%">
userEmotion이나 coupleEmotion에는 feedDate만 나와 있는데 피그마 상으로는 시간까지 보여주다보니 여쭤봤던 겁니다.!


<img src="https://github.com/user-attachments/assets/61b86907-4df4-4403-a153-b973f2f064db" width="30%">
<img src="https://github.com/user-attachments/assets/d52ef008-1d84-4d01-849a-807e1e5d886a" width="30%">

questionsWithAnswers에서 question은 하루에 하나만 있는 걸로 알고 있어서 리스트 형태로는 필요 없을 것 같습니다. 만약 하루에 질문이 여러개라면 수정하지 않으셔도 됩니다.
그리고 answers 부분에서도 프로필 정보랑 생성 날짜나 수정 날짜도 같이 있어야 할 것 같습니다.!

**Comment by saokiritoni** [comment]
@yoonth95  알겠습니다! 피그마상에서 '첫번째 질문' 이런 식으로 되어있어서 여러개라구 생각했어요! Answer이나 emotion 등등 필요한 부분 모두 프로필 사진, 닉네임, 본인 여부 같이 반환하도록 일괄적으로 적용해두겠습니다!

**Comment by yoonth95** [comment]
@saokiritoni 
소은님 죄송합니다 또... 있는데 날짜 별 피드 전체 가져오는 부분이나 감정 가져오는 부분 여쭤봤는데 감정도 board와 마찬가지로 여러 개일 수 있다고 하시네요 지금 API는 단일로만 가져오고 있어서 이것도 리스트 형태로 바꿔주시면 감사하겠습니다...

![image](https://github.com/user-attachments/assets/cd6b1774-59c0-488b-b585-b44494d1e83e)

**Comment by yoonth95** [comment]
커뮤니티에는 likedByUser가 있는데, board에는 없어서 추가 해주실 수 있나요...

**Comment by saokiritoni** [comment]
> @saokiritoni 소은님 죄송합니다 또... 있는데 날짜 별 피드 전체 가져오는 부분이나 감정 가져오는 부분 여쭤봤는데 감정도 board와 마찬가지로 여러 개일 수 있다고 하시네요 지금 API는 단일로만 가져오고 있어서 이것도 리스트 형태로 바꿔주시면 감사하겠습니다...
> 
에에에에 네 알겠습니다 ㅠㅠ..

**Comment by saokiritoni** [comment]
> 커뮤니티에는 likedByUser가 있는데, board에는 없어서 추가 해주실 수 있나요...

네넵!

**Comment by saokiritoni** [comment]
> @saokiritoni 소은님 죄송합니다 또... 있는데 날짜 별 피드 전체 가져오는 부분이나 감정 가져오는 부분 여쭤봤는데 감정도 board와 마찬가지로 여러 개일 수 있다고 하시네요 지금 API는 단일로만 가져오고 있어서 이것도 리스트 형태로 바꿔주시면 감사하겠습니다...

@yoonth95 
이 부분은 반영 완료했습니다! board에 좋아요 아직 추가 안 했더라구요.. 왜 체크해놨지..ㅎㅎㅎ 좋아요 해놓겠습니다 아직은 없어요!

**Comment by yoonth95** [comment]
@saokiritoni 

![image](https://github.com/user-attachments/assets/bbb08155-ea5d-490a-b618-f29f5f18a881)

피드 글 작성할 때 13일 새벽 2시에 작성을 했는데 feedDate는 12일로 저장이 되더라구요?
그래서 글은 13일에 작성했는데도 12일 날짜에 조회가 돼요...
저장 시간이 안 맞는 것 같아요

**Comment by yoonth95** [comment]
@saokiritoni 

날짜 별 feed 전체 조회에서는 본인이랑 커플 데이터 구분되어 들어와서 mine이 true, false 잘 나오는데,
board 상세 페이지에서는 배우자가 작성한 글도 mine이 true로 나와요... 

이건 메인 페이지 날짜 별 feed 조회 입니다. **/api/feeds/{date}**
<img src="https://github.com/user-attachments/assets/14e32c1b-ec6a-4116-a854-619297fcda51" width="40%" />

이거는 board 상세 페이지 조회입니다. **/api/feeds/boards/{boardId}**
<img src="https://github.com/user-attachments/assets/79fa779f-cf0e-44f3-b57e-d0f4b8be752d" width="40%" />

**Comment by yoonth95** [comment]
@saokiritoni 

board 글 수정 현재 body 값이 일반 string으로 받고 있습니다. 근데 글, 이미지도 같이 받아야 할 것 같아서요
글 추가랑 똑같이 해주면 될 것 같아요.!

![image](https://github.com/user-attachments/assets/9cb71a17-096f-4d5e-8132-1768a7a1b310)

**Comment by yoonth95** [comment]
@saokiritoni 

<img src="https://github.com/user-attachments/assets/394823fe-3576-4513-abf5-321027c5e12d" width="40%" />

댓글 추가할 때 (body 값이 "string" 이라고 나오는데, JSON 형식이 아닌가요? 계속 이상하게 들어갑니다) 아래처럼이면 될 것 같아요 
```
{
   "content": "string"
}
```

**Comment by yoonth95** [comment]
@saokiritoni 

네... 많아서 죄송합니다 ㅠㅠ 
혹시 댓글 수정 기능은 없을까요? 기획에는 있어서...

**Comment by saokiritoni** [comment]
@yoonth95 
1. 아니요 json 맞아요! 제 거에서 타입이 string이고 보낼때 json으로 보내주시면 돼요!!!! 전부 다 그래요
2. 수정 넣겠습니다!!! ㅠㅠ
3. board 다시 체크하겠습니다!!

**Comment by saokiritoni** [comment]
> 우자가 작성한 글도 mine이

@yoonth95 수정했습니다 5-10분뒤에 확인해주세요!!

**Comment by saokiritoni** [comment]
> board 글 수정 현재 body 값이 일반 string으로 받고 있습니다. 근데 글, 이미지도 같이 받아야 할 것 같아서요 글 추가랑 똑같이 해주면 될 것 같아요.!

@yoonth95 수정했습니다 5-10분뒤에 확인해주세요!!

**Comment by saokiritoni** [comment]
> 커뮤니티에는 likedByUser가 있는데, board에는 없어서 추가 해주실 수 있나요...
@yoonth95 수정했습니다 5-10분뒤에 확인해주세요!!

**Comment by yoonth95** [comment]
@saokiritoni 

근데 댓글 추가할 때, 아래처럼 보낼 때 저렇게 저장 되는데 왜 이러는지 알 수 있을까요?

![image](https://github.com/user-attachments/assets/f9be60c3-1505-41ba-a1ba-a38d22411646)
![image](https://github.com/user-attachments/assets/c8b9132f-275b-4295-83e9-8454ad146c44)

**Comment by saokiritoni** [comment]
@yoonth95  으아악 수정했습니다 5-10분 뒤에 확인해주세요!
