### ISSUE TITLE
✨ [Feature] - 피드: question

### ISSUE THREAD

**Issue by saokiritoni** [duobloom/DuoBloom-BE#8]
### ✅ To Do List

---
- [x] 공통 질문 조회 (날짜별 조회)
- [x] 공통 질문 답 업로드 (업로드 시 5포인트 적립)
- [x] 공통 질문 답 수정
- [x] request body --> feedDate등 자동 반영되게 수정
- [x] 반환값 수정

### 📚 Etc

---
- 완료 이후 피드 조회 (해당 날짜에 대한 감정, 질문, 글 조회) 구현할 것

**Comment by yoonth95** [comment]
@saokiritoni 

![image](https://github.com/user-attachments/assets/2d5acf6e-f654-470b-ad08-ab667ebeb090)

답변 (answer 테이블)에서는 db에는 13일로 저장되어 있는데 api 호출시에는 12일로 나옵니다.
시간이 다르게 나오는데 왜 그런지...

**Comment by yoonth95** [comment]
@saokiritoni 

제가 user_id 3번인데 날짜에 따른 전체 피드 조회할 때, board나 emotion은 다른 유저가 작성한 것들이 안 나오는데, 질문 답변에서 다른 유저의 답변이 나와요
사진을 보면 저는 user_id 3번으로 로그인을 했는데 12일 날짜로 user_id 1, 2번의 답변이 나오고 있는 상황입니다.!

<img src="https://github.com/user-attachments/assets/e4d9fcc4-9358-4e9f-a7c1-0488460ea1cc" width="40%">

**Comment by saokiritoni** [comment]
> 제가 user_id 3번인데 날짜에 따른 전체 피드 조회할 때, board나 emotion은 다른 유저가 작성한 것들이 안 나오는데, 질문 답변에서 다른 유저의 답변이 나와요 사진을 보면 저는 user_id 3번으로 로그인을 했는데 12일 날짜로 user_id 1, 2번의 답변이 나오고 있는 상황입니다.!
 
@yoonth95 
해결이 되었는지 잘 모르겠는데 한 5분 이따가 다시 확인해주세요!

**Comment by saokiritoni** [comment]
아니에요 다시 좀만 더 고칠게요...

**Comment by saokiritoni** [comment]
해결 되었는지 확인해주세요!! @yoonth95

**Comment by yoonth95** [comment]
@saokiritoni 

엇 네.! 잘 나오는 것 같아요

**Comment by yoonth95** [comment]
@saokiritoni 

질문에 대한 답변을 작성할 경우 작성자에게 5 포인트가 추가 되어야 하는데, 그 기능은 혹시 있을까요?
답변 삭제는 기획이 없기 때문에 추가된 포인트는 삭감하지는 않습니다

**Comment by saokiritoni** [comment]
@yoonth95 네 있습니다!

**Comment by yoonth95** [comment]
@saokiritoni 

엇.! 그러면 답변을 하면 자동으로 유저 포인트도 쌓이는 걸까요? 아니면 클라이언트 측에서 따로 해야 될 게 있을까요??

**Comment by saokiritoni** [comment]
@yoonth95 따로 할 건 없습니다!!

```java
@Transactional
    public void createAnswer(AnswerDto answerDto, Long userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new RuntimeException("User not found: " + userId));

        Question question = questionRepository.findById(answerDto.getQuestionId())
                .orElseThrow(() -> new RuntimeException("Question not found"));

        Answer answer = new Answer(user, question, answerDto.getContent());
        answerRepository.save(answer);

        increasePoints(user, 5);
    }
```

자동으로 적립되게 해두었습니다 !
